#!/usr/bin/env python3
import json,os
from pathlib import Path
R=Path(__file__).resolve().parent
def main():
 c=json.loads((R/'CONTRACT.json').read_text());s=json.loads((R/'CURRENT_STANDING.json').read_text());o=(R/'admission_gate.py').read_text();checks=[]
 def x(v,n):checks.append((n,bool(v)));assert v,n
 x(c['schema']=='axm-asoiaf-agot-review-admission-effect-gate/2','schema');x(c['componentId']=='asoiaf-agot-review-admission-effect-gate-v2','component');x(len(c['acceptedActions'])==6,'actions');x(c['actorSeparation']['admissionAndEffectActorsDistinct'] is True,'actors');x('read-private-source' in c['forbiddenOperations'],'private');x('create-git-commit' in c['forbiddenOperations'],'commit');x('open-pull-request' in c['forbiddenOperations'],'pr');x('execute-canon-mutation' in c['forbiddenOperations'],'canon');x('execute-graph-mutation' in c['forbiddenOperations'],'graph');x(c['authorityBoundary']['sourceAdmissionIsNotRepositoryMerge'] is True,'admission boundary');x(c['authorityBoundary']['effectPacketIsNotEffectExecution'] is True,'effect boundary');x(s['status']=='HOLD_REAL_VALIDATED_INTAKE_AND_SEPARATE_AUTHORIZATIONS','hold');x(s['realTransactionsAdmitted']==0,'zero transactions');x(s['realEffectPacketsSealed']==0,'zero packets');x(s['automaticCanonPromotions']==0,'zero canon');x(s['automaticGraphMutations']==0,'zero graph');x('REFUSE_SOURCE_TEXT_FIELD' in o,'source refusal');x('REFUSE_ACTOR_COLLISION' in o,'actor refusal');x('REFUSE_OUTPUT_DIVERGENCE' in o,'divergence');x('PASS_TRANSACTION_ADMITTED_TO_LEDGER_PENDING_EFFECT_PACKET' in o,'ledger standing');x('PASS_REPOSITORY_EFFECT_PACKET_SEALED_PENDING_SEPARATE_PR' in o,'packet standing');x('os.replace' in o and 'os.fsync' in o,'atomic');x('subprocess' not in o,'no subprocess');x(os.environ.get('PYTHONWARNINGS')=='error','warnings');assert len(checks)==24
 r={'schema':'axm-asoiaf-agot-review-admission-effect-gate-verification/2','componentId':c['componentId'],'status':'PASS','passed':len(checks),'total':len(checks),'failed':0,'warningsAsErrors':True,'realTransactionsAdmitted':0,'realEffectPacketsSealed':0,'repositoryMutationsExecuted':0,'automaticCanonPromotions':0,'automaticGraphMutations':0};print(json.dumps(r,indent=2,sort_keys=True));return 0
if __name__=='__main__':raise SystemExit(main())
